### ISSUE TITLE
Teleport command [Request]

### ISSUE THREAD

**Issue by Serux18** [AddstarMC/geSuitTeleport#9]
I propose to add a feature to change the teleportation command.
Example : gtp, gtpa, ...

To distinguish themselves from essentials, as I like to have both teleport by server as bungeecord.

Thx for read

PD: I would also like to be a variable to display the server from which you send teleport

**Comment by addstar** [comment]
Sorry, but we like the command the way it is. The geSuitTeleport plugin was not meant to be used with Essentials. But if you really want to do that, you can edit the `plugin.yml` inside the jar and change the command to whatever you like.
